import numpy as np
import math
from flatbuffers.packer import int16
from more_itertools.recipes import reshape

a = np.arange(15).reshape((3,5))
print("a = np.arange(15).reshape((3,5)):\n",a)
print("a.shape: ",a.shape)
print("a.ndim: ",a.ndim)
print("a.dtype.name: ",a.dtype.name)
print("a.itemsize:", a.itemsize)
print("a.size:",a.size)
print("type(a): ",type(a))

print()
print("-----Array creation-----")
print()
a = np.array([[2,3,4]])
print("a = np.array([[2,3,4]]): \n",a)
print("a.dtype: ",a.dtype)
b = np.array([1.2, 3.5, 5.1])
print("b.dtype: ",b.dtype)

print("a frequent error - multiple arguments instead of a sequence")
a = np.array([1,2,3,4])
print("a = np.array(1,2,3,4) is a wrong allocation")
print("a = np.array([1,2,3,4]) is a correct allocation")
print()
b=np.array([(1.5, 2, 3),(4, 5, 6)])
print("b=np.array([(1.5, 2, 3),(4, 5, 6)]): \n",b)
print("b.dtype: ",b.dtype)
print()
print("The type of the array can also be explicitly specified at creation time:")
c = np.array([[1, 2], [3, 4]], dtype=np.complex128)
print("c:\n: ",c)
print("c.dtype: ",c.dtype)
print()
print("np arrays > zeros, ones and empty")
print("np.zeros((3,4)):\n",np.zeros((3,4)))
print("np.ones((2, 3, 4)):\n",np.ones((2, 3, 4)))
print("np.empty((2, 3)):\n",np.empty((2, 3)))
print("np.ones((2, 3, 4),, dtype=np.int16):\n",np.ones((2, 3, 4), dtype=np.int16))
print()
print("create sequences of numbers > arange function")
print("np.arange(10, 30, 5):\n",np.arange(10, 30, 5))
print("np.arange of floats")
print("np.arange(0, 2, 0.3):\n",np.arange(0, 2, 0.3))
print()
print("function linspace > argument is the number of elements that we want, instead of the step:")
print("np.linspace(0, 2, 9):\n",np.linspace(0, 2, 9))
print()
print("useful to evaluate function at lots of points")
print("np.linspace(0, 2 * math.pi, 100):\n",np.linspace(0, 2 * math.pi, 100))
x = np.linspace(0, 2 * math.pi, 100)
print("np.sin(x):\n",np.sin(x))
print()
print("-----Printing arrays-----")
a = np.arange(6)
print("np.arange(6):\n",a)
b= np.arange(12).reshape(3,4)
print("np.arange(12):\n",b)
c = np.arange(24).reshape(2,3,4)
print("np.arange(24):\n",c)
print()
print("If an array is too large, numpy only prints the corners")
print("np.arange(10000):\n",np.arange(10000))
print("np.arange(10000).reshape(100, 100)\n",np.arange(10000).reshape(100, 100))

import sys
np.set_printoptions(threshold=sys.maxsize)
print("np.arange(10000).reshape(100, 100)\n",np.arange(10000).reshape(100, 100))
print()
print("-----Basic operations-----")
a = np.array([20, 30, 40, 50])
b = np.arange(4)
print("np.array([20, 30, 40, 50]):\n",a)
print("b = np.arange(4):\n",b)
c= a-b
print("c = a - b :\n",c)
print("b ** 2 :\n",b**2)
print("10 * np.sin(a) :\n",10 * np.sin(a))
print("a < 35: \n",a < 35)
print()
print("Demo of *, @ or .(dot)")
A = np.array([[1,1],
              [0,1]])
print("A:\n", A)
B = np.array([[2,0],
              [3,4]])
print("B:\n", B)
print("A*B: \n",A*B)
print("A@B: \n",A@B)
print("A.B: \n",A.dot(B))
print()
print("operations, such as += and *=, act in place to modify an existing array rather than create a new one.")
rg = np.random.default_rng(1)
print("rg = np.random.default_rng(1)")
a = np.ones((2,3), dtype=np.int_)
print("a=np.ones((2,3), dtype=np.int_):\n",a)
b=rg.random((2,3))
print("b = rg.random((2,3)):\n",b)
b += a
print("b += a: \n", b)
print()
print("Upcasting demo")
a = np.ones(3, dtype=np.int_)
b = np.linspace(0, math.pi, 3)
print("a=np.ones((3,3), dtype=np.int_):\n",a)
print("b=np.ones((3,3), dtype=np.int_):\n",b)
print("b.dtype.name: ",b.dtype.name)
c = a + b
print("c=a + b :\n",c)
d = np.exp(c * 1j)
print("d=np.exp(c * 1j):\n",d)
print("d.dtype.name:", d.dtype.name)