import numpy as np
import math
from flatbuffers.packer import int16

a = np.arange(15).reshape((3,5))
print("a = np.arange(15).reshape((3,5)):\n",a)
print("a.shape: ",a.shape)
print("a.ndim: ",a.ndim)
print("a.dtype.name: ",a.dtype.name)
print("a.itemsize:", a.itemsize)
print("a.size:",a.size)
print("type(a): ",type(a))

print()
print("-----Array creation-----")
print()
a = np.array([[2,3,4]])
print("a = np.array([[2,3,4]]): \n",a)
print("a.dtype: ",a.dtype)
b = np.array([1.2, 3.5, 5.1])
print("b.dtype: ",b.dtype)

print("a frequent error - multiple arguments instead of a sequence")
a = np.array([1,2,3,4])
print("a = np.array(1,2,3,4) is a wrong allocation")
print("a = np.array([1,2,3,4]) is a correct allocation")
print()
b=np.array([(1.5, 2, 3),(4, 5, 6)])
print("b=np.array([(1.5, 2, 3),(4, 5, 6)]): \n",b)
print("b.dtype: ",b.dtype)
print()
print("The type of the array can also be explicitly specified at creation time:")
c = np.array([[1, 2], [3, 4]], dtype=np.complex128)
print("c:\n: ",c)
print("c.dtype: ",c.dtype)
print()
print("np arrays > zeros, ones and empty")
print("np.zeros((3,4)):\n",np.zeros((3,4)))
print("np.ones((2, 3, 4)):\n",np.ones((2, 3, 4)))
print("np.empty((2, 3)):\n",np.empty((2, 3)))
print("np.ones((2, 3, 4),, dtype=np.int16):\n",np.ones((2, 3, 4), dtype=np.int16))
print()
print("create sequences of numbers > arange function")
print("np.arange(10, 30, 5):\n",np.arange(10, 30, 5))
print("np.arange of floats")
print("np.arange(0, 2, 0.3):\n",np.arange(0, 2, 0.3))
print()
print("function linspace > argument is the number of elements that we want, instead of the step:")
print("np.linspace(0, 2, 9):\n",np.linspace(0, 2, 9))
print()
print("useful to evaluate function at lots of points")
print("np.linspace(0, 2 * math.pi, 100):\n",np.linspace(0, 2 * math.pi, 100))
x = np.linspace(0, 2 * math.pi, 100)
print("np.sin(x):\n",np.sin(x))